main: me.Short.TheosisEconomy.TheosisEconomy
name: TheosisEconomy
version: '1.44'

author: Short
api-version: 1.13

load: STARTUP # This is needed because some plugins won't detect won't detect TheosisEconomy as an economy provider otherwise

depend: [Vault]

softdepend: [PlaceholderAPI, LiteBans]

commands:
  economy:
    description: Manage the economy.
    permission: theosiseconomy.command.economy
    aliases:
      - eco

  balance:
    description: See your own or another player's balance.
    permission: theosiseconomy.command.balance
    aliases:
      - bal
      - money

  balancetop:
    description: See a list of all players' balances from richest to poorest, and the combined total balance of all players.
    permission: theosiseconomy.command.balancetop
    aliases:
      - baltop

  pay:
    description: Pay another player a specified amount of money.
    permission: theosiseconomy.command.pay

  paytoggle:
    description: Toggle whether you want other players to be able to pay you money with the "/pay" command.
    permission: theosiseconomy.command.paytoggle

permissions:
  theosiseconomy.balancetop.exclude:
    description: Players with this permission will be excluded from the /balancetop list.
    default: op

  theosiseconomy.command.*:
    description: Access to all TheosisEconomy commands and sub-commands.
    default: op
    children:
      theosiseconomy.command.economy.*: true
      theosiseconomy.command.balance: true
      theosiseconomy.command.balance.others: true
      theosiseconomy.command.pay: true

  theosiseconomy.command.economy.*:
    description: Access to /economy and all of its sub-commands.
    default: op
    children:
      theosiseconomy.command.economy: true
      theosiseconomy.command.economy.set: true
      theosiseconomy.command.economy.give: true
      theosiseconomy.command.economy.take: true
      theosiseconomy.command.economy.reset: true
      theosiseconomy.command.economy.reload: true

  theosiseconomy.command.economy:
    description: Access to /economy.
    default: op

  theosiseconomy.command.economy.set:
    description: Access to /economy set <player> <amount>.
    default: op

  theosiseconomy.command.economy.give:
    description: Access to /economy give <player> <amount>.
    default: op

  theosiseconomy.command.economy.take:
    description: Access to /economy take <player> <amount>.
    default: op

  theosiseconomy.command.economy.reset:
    description: Access to /economy reset <player>.
    default: op

  theosiseconomy.command.economy.reload:
    description: Access to /economy reload.
    default: op

  theosiseconomy.command.balance:
    description: Access to /balance.
    default: true

  theosiseconomy.command.balance.others:
    description: Access to /balance [player].
    default: true

  theosiseconomy.command.balancetop:
    description: Access to /balancetop.
    default: true

  theosiseconomy.command.pay:
    description: Access to /pay.
    default: true

  theosiseconomy.command.paytoggle:
    description: Access to /paytoggle.
    default: true